[workspace]
resolver = "2"
members = [ "ftgo-accounting-service", "ftgo-api-gateway", "ftgo-auth-service",
    "ftgo-consumer-service", "ftgo-delivery-service",
    "ftgo-kitchen-service", "ftgo-order-service",
    "ftgo-proto",
    "ftgo-restaurant-service",
]
