services:
  ### Restaurant
  restaurant-rpc:
    image: ftgo-restaurant-rpc
    build:
      context: .
      args:
        - PACKAGE=ftgo-restaurant-service
        - BINARY=rpc
    environment:
      DATABASE_URL: postgres://postgres@restaurant-db/restaurant
      KAFKA_URL: kafka:9094
    ports:
      - 8101:8101
    depends_on:
      - restaurant-db

  restaurant-producer:
    image: ftgo-restaurant-producer
    build:
      context: .
      args:
        - PACKAGE=ftgo-restaurant-service
        - BINARY=producer
    environment:
      DATABASE_URL: postgres://postgres@restaurant-db/restaurant
      KAFKA_URL: kafka:9094

  ### Consumer
  consumer-rpc:
    image: ftgo-consumer-rpc
    build:
      context: .
      args:
        - PACKAGE=ftgo-consumer-service
        - BINARY=rpc
    environment:
      DATABASE_URL: postgres://postgres@consumer-db/consumer
      KAFKA_URL: kafka:9094
    ports:
      - 8102:8102
    depends_on:
      - consumer-db

  consumer-producer:
    image: ftgo-consumer-producer
    build:
      context: .
      args:
        - PACKAGE=ftgo-consumer-service
        - BINARY=producer
    environment:
      DATABASE_URL: postgres://postgres@consumer-db/consumer
      KAFKA_URL: kafka:9094

  consumer-consumer:
    image: ftgo-consumer-consumer
    build:
      context: .
      args:
        - PACKAGE=ftgo-consumer-service
        - BINARY=consumer
    environment:
      DATABASE_URL: postgres://postgres@consumer-db/consumer
      KAFKA_URL: kafka:9094

  ### Kitchen
  kitchen-rpc:
    image: ftgo-kitchen-rpc
    build:
      context: .
      args:
        - PACKAGE=ftgo-kitchen-service
        - BINARY=rpc
    environment:
      DATABASE_URL: postgres://postgres@kitchen-db/kitchen
      KAFKA_URL: kafka:9094
    ports:
      - 8105:8105
    depends_on:
      - kitchen-db

  kitchen-producer:
    image: ftgo-kitchen-producer
    build:
      context: .
      args:
        - PACKAGE=ftgo-kitchen-service
        - BINARY=producer
    environment:
      DATABASE_URL: postgres://postgres@kitchen-db/kitchen
      KAFKA_URL: kafka:9094

  kitchen-consumer:
    image: ftgo-kitchen-consumer
    build:
      context: .
      args:
        - PACKAGE=ftgo-kitchen-service
        - BINARY=consumer
    environment:
      DATABASE_URL: postgres://postgres@kitchen-db/kitchen
      KAFKA_URL: kafka:9094

  ### Delivery
  delivery-rpc:
    image: ftgo-delivery-rpc
    build:
      context: .
      args:
        - PACKAGE=ftgo-delivery-service
        - BINARY=rpc
    environment:
      DATABASE_URL: postgres://postgres@delivery-db/delivery
      KAFKA_URL: kafka:9094
    ports:
      - 8108:8108
    depends_on:
      - delivery-db

  delivery-producer:
    image: ftgo-delivery-producer
    build:
      context: .
      args:
        - PACKAGE=ftgo-delivery-service
        - BINARY=producer
    environment:
      DATABASE_URL: postgres://postgres@delivery-db/delivery
      KAFKA_URL: kafka:9094

  delivery-consumer:
    image: ftgo-delivery-consumer
    build:
      context: .
      args:
        - PACKAGE=ftgo-delivery-service
        - BINARY=consumer
    environment:
      DATABASE_URL: postgres://postgres@delivery-db/delivery
      KAFKA_URL: kafka:9094

  ### Database
  restaurant-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=restaurant
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
    ports:
      - 8201:5432
  consumer-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=consumer
    volumes:
      - consumer-db-data:/var/lib/postgresql/data
    ports:
      - 8202:5432
  order-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=order
    volumes:
      - order-db-data:/var/lib/postgresql/data
    ports:
      - 8203:5432
  kitchen-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=kitchen
    volumes:
      - kitchen-db-data:/var/lib/postgresql/data
    ports:
      - 8205:5432
  delivery-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=delivery
    volumes:
      - delivery-db-data:/var/lib/postgresql/data
    ports:
      - 8208:5432

  accounting-db:
    image: docker.eventstore.com/eventstore/eventstoredb-ee:24.10
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "8204:2113"
    volumes:
      - type: volume
        source: accounting-db-data
        target: /var/lib/eventstore
      - type: volume
        source: accounting-db-logs
        target: /var/log/eventstore
  accounting-projection-db:
    restart: always
    image: postgres:17-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=accounting
    volumes:
      - accounting-projection-db-data:/var/lib/postgresql/data
    ports:
      - 8304:5432

  kafka:
    image: apache/kafka-native:3.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093,DOCKER://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8989:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    depends_on:
      - kafka

  kafka-init:
    image: apache/kafka
    depends_on:
      - kafka
    restart: no
    command: >
      sh -c "
      /opt/kafka/bin/kafka-topics.sh --create --topic "restaurant.event" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "consumer.event" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "consumer.command" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "delivery.event" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "kitchen.event" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "kitchen.command" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "accounting.event" \\
        --bootstrap-server kafka:9094 --if-not-exists;

      /opt/kafka/bin/kafka-topics.sh --create --topic "accounting.command" \\
        --bootstrap-server kafka:9094 --if-not-exists;
      "

volumes:
  restaurant-db-data: {}
  consumer-db-data: {}
  kitchen-db-data: {}
  order-db-data: {}
  delivery-db-data: {}
  accounting-db-data: {}
  accounting-db-logs: {}
  accounting-projection-db-data: {}
